Added: migrate to check if doc needs updating.

diff --git a/sh/test b/sh/test
--- a/sh/test
+++ b/sh/test
@@ -1,7 +1,9 @@
 #!/usr/bin/env bash
 #
 #
-set -u -e -o pipefail -x
+set -u -e -o pipefail
 
-IS_TEST="yes" FORCE_COLOR=true secrets FAUNA_TEST_A \
-  node spec/main.mjs "$*"
+export IS_TEST="yes"
+export FORCE_COLOR=true
+secrets FAUNA_TEST_A \
+  node spec/main.mjs "$*" && echo -e "\n ==== \e[32m PASSED \e[m  ====\n" || echo -e "\n !!! \e[31m FAILED \e[m !!!\n"
